# .github/workflows/test_flask_api.yml
name: Test Flask API

# Trigger the workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps to execute the job
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flask langchain_openai sentence-transformers huggingface_hub torch

      # Step 4: Run the Flask app in the background
      - name: Run Flask app
        run: |
          python -m flask run --host=0.0.0.0 --port=8001 &
        env:
          FLASK_APP: app.py
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Ensure that the OpenAI API key is set in GitHub secrets

      # Step 5: Test the /get_embedding endpoint with curl
      - name: Test /get_embedding endpoint
        run: |
          sleep 5  # Wait for Flask server to start
          curl -X POST http://localhost:8001/get_embedding \
            -H "Content-Type: application/json" \
            -d '{"text": "Your sample text here"}'

      # Step 6: Stop the Flask server (optional if you want to clean up)
      - name: Stop Flask app
        run: |
          kill $(lsof -t -i:8001)